import json
from pathlib import Path

data = {
  "source": "Agricultural and Veterinary Chemicals (MRL Standard for Residues of Chemical Products) Instrument 2023",
  "jurisdiction": "Australia (APVMA)",
  "document_id": "F2026C00845",
  "compilation_no": 16,
  "compilation_date": "2026-08-21",
  "unit": "mg/kg (fresh weight, unless otherwise noted)",
  "flag_legend": {
    "T": "Temporary MRL/ERL, or use, subject to review",
    "E": "ERL (Extraneous Residue Limit) rather than MRL",
    "*": "MRL/ERL set at or about the limit of analytical quantitation"
  },
  "record_count": 6174,
  "compound_count": 471,
  "records": [
    {"compound":"Abamectin","food_code":"VD 0560","food_commodity":"Adzuki bean (dry)","mrl_raw":"*0.002","mrl_value_mg_per_kg":0.002,"mrl_flags":"*"},
    {"compound":"Abamectin","food_code":"TN 0660","food_commodity":"Almonds","mrl_raw":"*0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":"*"},
    {"compound":"Abamectin","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"FB 0020","food_commodity":"Blueberries","mrl_raw":"T0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":"T"},
    {"compound":"Abamectin","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"*0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":"*"},
    {"compound":"Abamectin","food_code":"VC 0424","food_commodity":"Cucumber","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"VL 0053","food_commodity":"Leafy vegetables","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},
    {"compound":"Abamectin","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"FI 0350","food_commodity":"Papaya [pawpaw]","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"VR 0075","food_commodity":"Root and tuber vegetables","mrl_raw":"*0.01","mrl_value_mg_per_kg":0.01,"mrl_flags":"*"},
    {"compound":"Abamectin","food_code":"FB 0275","food_commodity":"Strawberry","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Abamectin","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},

    {"compound":"Acetamiprid","food_code":"FP 0226","food_commodity":"Apple","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Acetamiprid","food_code":"FB 0020","food_commodity":"Blueberries","mrl_raw":"T0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":"T"},
    {"compound":"Acetamiprid","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Acetamiprid","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Acetamiprid","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Acetamiprid","food_code":"FP 0230","food_commodity":"Pear","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Acetamiprid","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},

    {"compound":"Azoxystrobin","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"3","mrl_value_mg_per_kg":3.0,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"GC 0640","food_commodity":"Barley","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"VR 0577","food_commodity":"Carrot","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"3","mrl_value_mg_per_kg":3.0,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"T0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":"T"},
    {"compound":"Azoxystrobin","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"FI 0350","food_commodity":"Papaya [pawpaw]","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Azoxystrobin","food_code":"GC 0649","food_commodity":"Rice","mrl_raw":"T7","mrl_value_mg_per_kg":7.0,"mrl_flags":"T"},
    {"compound":"Azoxystrobin","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"T1","mrl_value_mg_per_kg":1.0,"mrl_flags":"T"},
    {"compound":"Azoxystrobin","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"T1","mrl_value_mg_per_kg":1.0,"mrl_flags":"T"},
    {"compound":"Azoxystrobin","food_code":"GC 0654","food_commodity":"Wheat","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},

    {"compound":"Boscalid","food_code":"FB 0020","food_commodity":"Blueberries","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"4","mrl_value_mg_per_kg":4.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"VL 0053","food_commodity":"Leafy vegetables","mrl_raw":"30","mrl_value_mg_per_kg":30.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"VO 0050","food_commodity":"Fruiting vegetables, other than cucurbits","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Boscalid","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},

    {"compound":"Captan","food_code":"TN 0660","food_commodity":"Almonds","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Captan","food_code":"FP 0226","food_commodity":"Apple","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Captan","food_code":"FB 0020","food_commodity":"Blueberries","mrl_raw":"20","mrl_value_mg_per_kg":20.0,"mrl_flags":""},
    {"compound":"Captan","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Captan","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Captan","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"15","mrl_value_mg_per_kg":15.0,"mrl_flags":""},
    {"compound":"Captan","food_code":"FB 0275","food_commodity":"Strawberry","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},

    {"compound":"Chlorothalonil","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"3","mrl_value_mg_per_kg":3.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"VR 0577","food_commodity":"Carrot","mrl_raw":"7","mrl_value_mg_per_kg":7.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"VS 0624","food_commodity":"Celery","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"FS 0247","food_commodity":"Peach","mrl_raw":"30","mrl_value_mg_per_kg":30.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"SO 0697","food_commodity":"Peanut","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"15","mrl_value_mg_per_kg":15.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"FB 0275","food_commodity":"Strawberry","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Chlorothalonil","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},

    {"compound":"Chlorpyrifos","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Chlorpyrifos","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},
    {"compound":"Chlorpyrifos","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},
    {"compound":"Chlorpyrifos","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"T1","mrl_value_mg_per_kg":1.0,"mrl_flags":"T"},
    {"compound":"Chlorpyrifos","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"*0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":"*"},
    {"compound":"Chlorpyrifos","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Chlorpyrifos","food_code":"GC 0649","food_commodity":"Rice","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Chlorpyrifos","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},
    {"compound":"Chlorpyrifos","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},

    {"compound":"Cypermethrin","food_code":"GC 0080","food_commodity":"Cereal grains","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Cypermethrin","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Cypermethrin","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"T0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":"T"},
    {"compound":"Cypermethrin","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Cypermethrin","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Cypermethrin","food_code":"GC 0654","food_commodity":"Wheat","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},

    {"compound":"Deltamethrin","food_code":"GC 0080","food_commodity":"Cereal grains","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Deltamethrin","food_code":"VO 0050","food_commodity":"Fruiting vegetables, other than cucurbits","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Deltamethrin","food_code":"SO 0088","food_commodity":"Oilseeds","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Deltamethrin","food_code":"VD 0070","food_commodity":"Pulses","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},

    {"compound":"Difenoconazole","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"T0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":"T"},
    {"compound":"Difenoconazole","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"*0.02","mrl_value_mg_per_kg":0.02,"mrl_flags":"*"},
    {"compound":"Difenoconazole","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Difenoconazole","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"T0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":"T"},
    {"compound":"Difenoconazole","food_code":"FI 0350","food_commodity":"Papaya [pawpaw]","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Difenoconazole","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Difenoconazole","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Difenoconazole","food_code":"GC 0649","food_commodity":"Rice","mrl_raw":"T7","mrl_value_mg_per_kg":7.0,"mrl_flags":"T"},

    {"compound":"Dimethoate","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"0.7","mrl_value_mg_per_kg":0.7,"mrl_flags":""},
    {"compound":"Dimethoate","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"5","mrl_value_mg_per_kg":5.0,"mrl_flags":""},
    {"compound":"Dimethoate","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Dimethoate","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.02","mrl_value_mg_per_kg":0.02,"mrl_flags":""},
    {"compound":"Dimethoate","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.02","mrl_value_mg_per_kg":0.02,"mrl_flags":""},

    {"compound":"Fludioxonil","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Fludioxonil","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"10","mrl_value_mg_per_kg":10.0,"mrl_flags":""},
    {"compound":"Fludioxonil","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Fludioxonil","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"3","mrl_value_mg_per_kg":3.0,"mrl_flags":""},
    {"compound":"Fludioxonil","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"5","mrl_value_mg_per_kg":5.0,"mrl_flags":""},
    {"compound":"Fludioxonil","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"T1","mrl_value_mg_per_kg":1.0,"mrl_flags":"T"},
    {"compound":"Fludioxonil","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"T1","mrl_value_mg_per_kg":1.0,"mrl_flags":"T"},

    {"compound":"Glyphosate","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"*0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":"*"},
    {"compound":"Glyphosate","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Glyphosate","food_code":"GC 0640","food_commodity":"Barley","mrl_raw":"20","mrl_value_mg_per_kg":20.0,"mrl_flags":""},
    {"compound":"Glyphosate","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Glyphosate","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"15","mrl_value_mg_per_kg":15.0,"mrl_flags":""},
    {"compound":"Glyphosate","food_code":"GC 0654","food_commodity":"Wheat","mrl_raw":"5","mrl_value_mg_per_kg":5.0,"mrl_flags":""},

    {"compound":"Imidacloprid","food_code":"FP 0226","food_commodity":"Apple","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"SO 0691","food_commodity":"Cotton seed","mrl_raw":"*0.02","mrl_value_mg_per_kg":0.02,"mrl_flags":"*"},
    {"compound":"Imidacloprid","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Imidacloprid","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},

    {"compound":"Mancozeb","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"T15","mrl_value_mg_per_kg":15.0,"mrl_flags":"T"},
    {"compound":"Mancozeb","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"T15","mrl_value_mg_per_kg":15.0,"mrl_flags":"T"},
    {"compound":"Mancozeb","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Mancozeb","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"T5","mrl_value_mg_per_kg":5.0,"mrl_flags":"T"},
    {"compound":"Mancozeb","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"T5","mrl_value_mg_per_kg":5.0,"mrl_flags":"T"},

    {"compound":"Metalaxyl","food_code":"FI 0326","food_commodity":"Avocado","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Metalaxyl","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Metalaxyl","food_code":"FS 0247","food_commodity":"Peach","mrl_raw":"0.6","mrl_value_mg_per_kg":0.6,"mrl_flags":""},
    {"compound":"Metalaxyl","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Metalaxyl","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},
    {"compound":"Metalaxyl","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"T0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":"T"},

    {"compound":"Permethrin","food_code":"GC 0080","food_commodity":"Cereal grains","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Permethrin","food_code":"VL 0482","food_commodity":"Lettuce, head","mrl_raw":"5","mrl_value_mg_per_kg":5.0,"mrl_flags":""},
    {"compound":"Permethrin","food_code":"VR 0589","food_commodity":"Potato","mrl_raw":"0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":""},
    {"compound":"Permethrin","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.4","mrl_value_mg_per_kg":0.4,"mrl_flags":""},
    {"compound":"Permethrin","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.4","mrl_value_mg_per_kg":0.4,"mrl_flags":""},

    {"compound":"Propiconazole","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Propiconazole","food_code":"GC 0080","food_commodity":"Cereal grains","mrl_raw":"*0.05","mrl_value_mg_per_kg":0.05,"mrl_flags":"*"},
    {"compound":"Propiconazole","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"7","mrl_value_mg_per_kg":7.0,"mrl_flags":""},
    {"compound":"Propiconazole","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},

    {"compound":"Pyraclostrobin","food_code":"GC 0640","food_commodity":"Barley","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"FB 0020","food_commodity":"Blueberries","mrl_raw":"4","mrl_value_mg_per_kg":4.0,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"2","mrl_value_mg_per_kg":2.0,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"1","mrl_value_mg_per_kg":1.0,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"VO 0050","food_commodity":"Fruiting vegetables, other than cucurbits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Pyraclostrobin","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},

    {"compound":"Spinetoram","food_code":"FB 0018","food_commodity":"Berries and other small fruits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Spinetoram","food_code":"FC 0001","food_commodity":"Citrus fruits","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Spinetoram","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Spinetoram","food_code":"FP 0009","food_commodity":"Pome fruits","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},
    {"compound":"Spinetoram","food_code":"FS 0012","food_commodity":"Stone fruits","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Spinetoram","food_code":"VO 0050","food_commodity":"Fruiting vegetables, other than cucurbits","mrl_raw":"0.1","mrl_value_mg_per_kg":0.1,"mrl_flags":""},

    {"compound":"Tebuconazole","food_code":"FI 0327","food_commodity":"Banana","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"GC 0080","food_commodity":"Cereal grains","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"FB 0269","food_commodity":"Grapes","mrl_raw":"5","mrl_value_mg_per_kg":5.0,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"FI 0345","food_commodity":"Mango","mrl_raw":"0.4","mrl_value_mg_per_kg":0.4,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"SO 0495","food_commodity":"Rape seed [canola]","mrl_raw":"0.3","mrl_value_mg_per_kg":0.3,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"VO 0050","food_commodity":"Fruiting vegetables, other than cucurbits","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"VO 0448","food_commodity":"Tomato","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"VO 0448","food_commodity":"Tomatoes","mrl_raw":"0.5","mrl_value_mg_per_kg":0.5,"mrl_flags":""},
    {"compound":"Tebuconazole","food_code":"GC 0654","food_commodity":"Wheat","mrl_raw":"0.2","mrl_value_mg_per_kg":0.2,"mrl_flags":""}
  ]
}

data_path = Path("ai-service/data/mrl_australia_table1.json")
data_path.parent.mkdir(parents=True, exist_ok=True)
data_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written {len(data['records'])} MRL records to {data_path}")

root_path = Path("mrl_australia_table1.json")
root_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written copy to {root_path}")
